[project]
name = "gene-expression-cancer"
version = "0.1.0"
description = "Analysis of cancer gene expression dataset"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "duckdb>=1.2.2",
    "flax>=0.10.6",
    "ipykernel>=6.29.5",
    "jax>=0.6.0",
    "marimo>=0.13.2",
    "matplotlib>=3.10.1",
    "optax>=0.2.4",
    "pandas>=2.2.3",
    "polars>=1.27.1",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "umap-learn>=0.5.7",
    "vegafusion[embed]>=2.0.2",
]
